### ISSUE TITLE
Need documentation for using Raster Tiles Sources

### ISSUE THREAD

**Issue by aymux** [razorness/vue-maplibre-gl#51]
After spending some time reading the source code, i cannot get a clue on how to use the mgl-raster-source component.

I don't understand either the props needed ( url - tiles - scheme etc )

Please could you give example or doc on how to use It ?

Thanks for your time ^^

**Comment by razorness** [comment]
Hey @aymux, the components basically get just mapped to their corresponding [style specification](https://maplibre.org/maplibre-gl-js-docs/style-spec/) and bound to the map instance.

Take a look a maplibre-gl documentation for [map-tiles](https://maplibre.org/maplibre-gl-js-docs/example/map-tiles/) and here is the [api definition](https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#raster).


You should be able to use [MglRasterSource](https://github.com/razorness/vue-maplibre-gl/blob/master/src/components/sources/raster.source.ts) and [MglRasterLayer](https://github.com/razorness/vue-maplibre-gl/blob/master/src/components/layers/raster.layer.ts) in a way like `MglGeoJsonSource` in this example:
https://github.com/razorness/vue-maplibre-gl/blob/fde5c521626ec000fd3363e0f1e0485f8ee52a41/dev/serve.vue#L28-L36

In this way, you are able to combine different sources to display f.e. GeoJSON over raster/vector map tiles or partially transparent raster tiles over vector tiles.

Maplibre needs a source definition and a layer definition.

**Comment by aymux** [comment]
Thank you i managed to inject style directly on main component mgl-map with mapStyle props

**Comment by razorness** [comment]
That's also fine.
