### ISSUE TITLE
Keep attribution in demo

### ISSUE THREAD

**Issue by frodrigo** [razorness/vue-maplibre-gl#68]
Remove the attribution is a bad practice. Avoid to do this in a demo.
https://www.openstreetmap.org/copyright

https://github.com/razorness/vue-maplibre-gl/blob/1b0284b1e37ec95102bb22e97414395664d33c06/src/App.vue#L9

**Comment by razorness** [comment]
You are right. That was just left over from a test if this prop gets applied.
